from dotenv import load_dotenv
load_dotenv()

from flask import (
    Flask, render_template, request,
    session, redirect, url_for, send_file
)

import os
import uuid
import traceback
from datetime import datetime, timedelta
from flask import send_file
from utils.email_service import send_welcome_email



from werkzeug.security import generate_password_hash, check_password_hash
from bson.objectid import ObjectId

# ================= UTILS =================
from utils.email_service import send_otp_email
from utils.validators import is_valid_email, is_strong_password
from utils.otp import generate_otp
from utils.avatar_selector import select_avatar

# ================= DATABASE =================
from database import users, reports

# ================= OCR & PARSING =================
from ocr.ocr_engine import extract_text
from ocr.lab_parser import extract_lab_values, sanitize_lab_values
from ocr.patient_parser import extract_patient_info
from ocr.medi_hub_detector import is_medihub_generated
from ocr.lab_flags import flag_lab_values
from ocr.lab_explanations import explain
from ocr.digital_report import generate_digital_report


# ================= ML MODELS =================
from ml.diabetes_ml import predict_diabetes_ml
from ml.anemia_ml import predict_anemia_ml
from ml.kidney_ml import predict_kidney_ml
from ml.cbc_ml import predict_cbc
from ml.report_classifier import detect_report_type

# ================= FLASK APP =================
app = Flask(__name__)
app.secret_key = "medical_ai_secret"

UPLOAD_FOLDER = "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# =================================================
# LOGIN CHECK
# =================================================
def login_required():
    return "user_id" in session


# =================================================
# INDEX → UPLOAD
# =================================================
@app.route("/", methods=["GET", "POST"])
def index():
    if not login_required():
        return redirect(url_for("login"))

    if request.method == "GET":
        return render_template("index.html", upload_done=False)

    try:
        file = request.files.get("report")
        if not file or file.filename == "":
            return render_template(
                "index.html",
                error="No file uploaded",
                upload_done=False
            )

        filename = f"{uuid.uuid4().hex}_{file.filename}"
        file_path = os.path.join(UPLOAD_FOLDER, filename)
        file.save(file_path)

        # OCR
        try:
            raw_text = extract_text(file_path)
            if not raw_text.strip():
                raw_text = "OCR_PENDING"
        except Exception:
            raw_text = "OCR_PENDING"

        if is_medihub_generated(raw_text):
            return render_template(
                "index.html",
                error="This report was generated by MediHub.",
                upload_done=False
            )

        lab_values = sanitize_lab_values(extract_lab_values(raw_text))
        flags = flag_lab_values(lab_values)
        patient = extract_patient_info(raw_text)

        # ✅ CLEAN OCR NOISE FROM NAME (FIXED LOCATION)
        if patient.get("name"):
            patient["name"] = (
                patient["name"]
                .replace("Age", "")
                .replace("AGE", "")
                .strip()
            )

        report_doc = {
            "user_id": session["user_id"],
            "original_file": filename,
            "raw_text": raw_text,
            "patient": patient,
            "lab_values": lab_values,
            "flags": flags,
            "created_at": datetime.utcnow()
        }

        result = reports.insert_one(report_doc)
        session["report_id"] = str(result.inserted_id)

        return render_template("index.html", upload_done=True)

    except Exception:
        traceback.print_exc()
        return render_template(
            "index.html",
            error="Unexpected error occurred",
            upload_done=False
        )


# =================================================
# DASHBOARD
# =================================================
@app.route("/analyze")
def analyze():
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one(
        {"user_id": session["user_id"]},
        sort=[("created_at", -1)]
    )
    if not report:
        return redirect(url_for("index"))

    patient = report.get("patient", {})
    lab_values = report.get("lab_values", {})
    flags = report.get("flags", {})

    explanations = {
        t: explain(t, d.get("status", "normal"))
        for t, d in flags.items()
    }

    try:
        age = int(patient.get("age"))
    except Exception:
        age = None

    avatar = select_avatar(age, patient.get("gender"))
    report_types = detect_report_type(lab_values)

    results = {}
    if "CBC" in report_types:
        results["CBC"] = predict_cbc(lab_values)
        results["Anemia"] = predict_anemia_ml(lab_values)

    if "Diabetes" in report_types:
        results["Diabetes"] = predict_diabetes_ml(lab_values)

    if "Kidney" in report_types:
        results["Kidney"] = predict_kidney_ml(lab_values)

    return render_template(
        "dashboard.html",
        patient=patient,
        avatar=avatar,
        lab_values=lab_values,
        flags=flags,
        explanations=explanations,
        report_types=report_types,
        results=results,
        recommendations=["Maintain a healthy lifestyle."]
    )


# =================================================
# DOCUMENTS
# =================================================
@app.route("/documents")
def documents():
    if not login_required():
        return redirect(url_for("login"))

    user_reports = list(
        reports.find({"user_id": session["user_id"]})
        .sort("created_at", -1)
    )

    return render_template(
        "documents.html",
        reports=user_reports,
        report_count=len(user_reports)
    )
# =================================================
# VIEW SINGLE REPORT
# =================================================
@app.route("/report/<report_id>")
def view_report(report_id):
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one({
        "_id": ObjectId(report_id),
        "user_id": session["user_id"]
    })

    if not report:
        return redirect(url_for("documents"))

    return render_template(
        "view_report.html",
        report=report,
        patient=report.get("patient", {}),
        lab_values=report.get("lab_values", {}),
        flags=report.get("flags", {})
    )

# =================================================
# DOWNLOAD REPORT
# =================================================
@app.route("/report/<report_id>/download")
def download_report(report_id):
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one({
        "_id": ObjectId(report_id),
        "user_id": session["user_id"]
    })

    if not report:
        return redirect(url_for("documents"))

    pdf_path = generate_digital_report(report)

    return send_file(
        pdf_path,
        as_attachment=True,
        download_name="Medical_Report.pdf"
    )



# =================================================
# DELETE REPORT
# =================================================
@app.route("/report/<report_id>/delete", methods=["POST"])
def delete_report(report_id):
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one({
        "_id": ObjectId(report_id),
        "user_id": session["user_id"]
    })

    if report:
        file_path = os.path.join(UPLOAD_FOLDER, report["original_file"])
        if os.path.exists(file_path):
            os.remove(file_path)

        reports.delete_one({"_id": ObjectId(report_id)})

    return redirect(url_for("documents"))




# =================================================
# REGISTER
# =================================================
@app.route("/register", methods=["GET", "POST"])
def register():
    # 🔹 GET → show register page
    if request.method == "GET":
        return render_template("register.html")

    # 🔹 POST → handle registration
    email = request.form.get("email")
    password = request.form.get("password")

    # ✅ EMAIL VALIDATION
    if not is_valid_email(email):
        return render_template(
            "register.html",
            error="Invalid email format"
        )

    # ✅ PASSWORD VALIDATION
    if not is_strong_password(password):
        return render_template(
            "register.html",
            error="Password must be at least 8 characters, include 1 capital letter and 1 special character"
        )

    # ✅ DUPLICATE CHECK
    if users.find_one({"email": email}):
        return render_template(
            "register.html",
            error="Email already registered"
        )

    # ✅ CREATE USER
    users.insert_one({
        "email": email,
        "password": generate_password_hash(
            password,
            method="pbkdf2:sha256"
        ),
        "created_at": datetime.utcnow()
    })

    # ✅ SEND WELCOME EMAIL (INFORMATIONAL)
    try:
        send_welcome_email(email)
    except Exception as e:
        print("Welcome email failed:", e)
        # Do NOT block registration if email fails

    # ✅ SHOW SUCCESS STATE (NO REDIRECT)
    return render_template(
        "register.html",
        success=True,
        email=email
    )


# =================================================
# LOGIN
# =================================================
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        user = users.find_one({"email": request.form["email"]})
        if not user or not check_password_hash(
            user["password"], request.form["password"]
        ):
            return render_template("login.html", error="Invalid credentials")

        session.clear()
        session["user_id"] = str(user["_id"])
        return redirect(url_for("index"))

    return render_template("login.html")


# =================================================
# FORGOT PASSWORD
# =================================================
@app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password():
    if request.method == "POST":
        email = request.form.get("email")

        if not is_valid_email(email):
            return render_template("forgot_password.html", error="Invalid email")

        user = users.find_one({"email": email})
        if not user:
            return render_template("forgot_password.html", error="Email not registered")

        otp = generate_otp()
        users.update_one(
            {"email": email},
            {"$set": {
                "reset_otp": otp,
                "otp_expiry": datetime.utcnow() + timedelta(minutes=10)
            }}
        )

        send_otp_email(email, otp)
        session["reset_email"] = email
        return redirect(url_for("reset_password"))

    return render_template("forgot_password.html")


# =================================================
# RESET PASSWORD
# =================================================
@app.route("/reset-password", methods=["GET", "POST"])
def reset_password():
    email = session.get("reset_email")
    if not email:
        return redirect(url_for("login"))

    if request.method == "POST":
        otp = request.form.get("otp")
        password = request.form.get("password")

        user = users.find_one({"email": email})
        if not user or user.get("reset_otp") != otp:
            return render_template("reset_password.html", error="Invalid OTP")

        if datetime.utcnow() > user.get("otp_expiry"):
            return render_template("reset_password.html", error="OTP expired")

        if not is_strong_password(password):
            return render_template("reset_password.html", error="Weak password")

        users.update_one(
            {"email": email},
            {
                "$set": {
                    "password": generate_password_hash(password, method="pbkdf2:sha256")
                },
                "$unset": {
                    "reset_otp": "",
                    "otp_expiry": ""
                }
            }
        )

        session.pop("reset_email", None)
        return render_template("reset_success.html")

    return render_template("reset_password.html")


# =================================================
# LOGOUT
# =================================================
@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# =================================================
# RUN
# =================================================
if __name__ == "__main__":
    app.run(port=5003, debug=False)
