from dotenv import load_dotenv
load_dotenv()

from flask import (
    Flask, render_template, request,
    session, redirect, url_for, send_file,abort
)

import os
import uuid
import traceback
from datetime import datetime, timedelta

from werkzeug.security import generate_password_hash, check_password_hash
from bson.objectid import ObjectId

# ================= UTILS =================
from utils.email_service import send_otp_email, send_welcome_email
from utils.validators import is_valid_email, is_strong_password
from utils.otp import generate_otp
from utils.avatar_selector import select_avatar

# ================= DATABASE =================
from database import users, reports

# ================= OCR & PARSING =================
from ocr.ocr_engine import extract_text
from ocr.lab_parser import extract_lab_values, sanitize_lab_values
from ocr.patient_parser import extract_patient_info
from ocr.medi_hub_detector import is_medihub_generated
from ocr.lab_flags import flag_lab_values
from ocr.lab_explanations import explain
from ocr.digital_report import generate_digital_report
from ocr.disease_predictor import predict_diseases

# ================= ML MODELS =================
from ml.diabetes_ml import predict_diabetes_ml
from ml.anemia_ml import predict_anemia_ml
from ml.kidney_ml import predict_kidney_ml
from ml.cbc_ml import predict_cbc
from ml.liver_ml import predict_liver_ml
from ml.report_classifier import detect_report_type

# ================= FLASK APP =================
app = Flask(__name__)
app.secret_key = os.getenv("FLASK_SECRET_KEY")

UPLOAD_FOLDER = "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)


# =================================================
# LOGIN CHECK
# =================================================
def login_required():
    return "user_id" in session

# =================================================
# UPLOAD PAGE
# =================================================
@app.route("/upload", methods=["GET", "POST"])
def index():
    if not login_required():
        return redirect(url_for("login"))

    if request.method == "GET":
        return render_template("index.html", upload_done=False)

    try:
        file = request.files.get("report")
        if not file or file.filename == "":
            return render_template(
                "index.html",
                error="No file uploaded",
                upload_done=False
            )

        filename = f"{uuid.uuid4().hex}_{file.filename}"
        file_path = os.path.join(UPLOAD_FOLDER, filename)
        file.save(file_path)

        # OCR
        try:
            raw_text = extract_text(file_path)
            if not raw_text.strip():
                raw_text = "OCR_PENDING"
        except Exception:
            raw_text = "OCR_PENDING"

        if is_medihub_generated(raw_text):
            return render_template(
                "index.html",
                error="This report was generated by MediHub.",
                upload_done=False
            )

                # =========================
        # LAB EXTRACTION
        # =========================
        lab_values = sanitize_lab_values(
            extract_lab_values(raw_text)
        )
        flags = flag_lab_values(lab_values)
        patient = extract_patient_info(raw_text)

        # =========================
        # DISEASE PREDICTION
        # =========================
        diseases = predict_diseases(lab_values)


        # CLEAN NAME
        if patient.get("name"):
            patient["name"] = (
                patient["name"]
                .replace("Age", "")
                .replace("AGE", "")
                .strip()
            )

        report_doc = {
            "user_id": session["user_id"],
            "original_file": filename,
            "raw_text": raw_text,
            "patient": patient,
            "lab_values": lab_values,
            "flags": flags,
            "diseases": diseases,
            "created_at": datetime.utcnow()
        }

        result = reports.insert_one(report_doc)
        session["report_id"] = str(result.inserted_id)

        return render_template("index.html", upload_done=True)

    except Exception:
        traceback.print_exc()
        return render_template(
            "index.html",
            error="Unexpected error occurred",
            upload_done=False
        )


# =================================================
# DASHBOARD
# =================================================
@app.route("/analyze")
def analyze():
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one(
        {"user_id": session["user_id"]},
        sort=[("created_at", -1)]
    )

    if not report:
        return redirect(url_for("index"))

    patient = report.get("patient", {})
    lab_values = report.get("lab_values", {})
    flags = report.get("flags", {})
    diseases = report.get("diseases", {})

    explanations = {
        t: explain(t, d.get("status", "normal"))
        for t, d in flags.items()
    }

    try:
        age = int(patient.get("age"))
    except Exception:
        age = None

    avatar = select_avatar(age, patient.get("gender"))
    report_types = detect_report_type(lab_values)

    results = {}
    if "CBC" in report_types:
        results["CBC"] = predict_cbc(lab_values)
        results["Anemia"] = predict_anemia_ml(lab_values)

    if "Diabetes" in report_types:
        results["Diabetes"] = predict_diabetes_ml(lab_values)

    if "Kidney" in report_types:
        results["Kidney"] = predict_kidney_ml(lab_values)
    if "Liver" in report_types:
        results["Liver"] = predict_liver_ml(lab_values, patient)


    return render_template(
        "dashboard.html",
        patient=patient,
        avatar=avatar,
        lab_values=lab_values,
        flags=flags,
        explanations=explanations,
        diseases=diseases,
        report_types=report_types,
        results=results,
        recommendations=["Maintain a healthy lifestyle."]
    )

# =================================================
# DOCUMENTS
# =================================================
@app.route("/documents")
def documents():
    if not login_required():
        return redirect(url_for("login"))

    user_reports = list(
        reports.find({"user_id": session["user_id"]})
        .sort("created_at", -1)
    )

    return render_template(
        "documents.html",
        reports=user_reports,
        report_count=len(user_reports)
    )
# =================================================
# VIEW SINGLE REPORT
# =================================================
@app.route("/report/<report_id>")
def view_report(report_id):
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one({
        "_id": ObjectId(report_id),
        "user_id": session["user_id"]
    })

    if not report:
        return redirect(url_for("documents"))

    return render_template(
        "view_report.html",
        report=report,
        patient=report.get("patient", {}),
        lab_values=report.get("lab_values", {}),
        flags=report.get("flags", {})
    )

# =================================================
# DOWNLOAD REPORT
# =================================================
@app.route("/report/<report_id>/download")
def download_report(report_id):
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one({
        "_id": ObjectId(report_id),
        "user_id": session["user_id"]
    })

    if not report:
        return redirect(url_for("documents"))

    pdf_path = generate_digital_report(report)

    return send_file(
        pdf_path,
        as_attachment=True,
        download_name="Medical_Report.pdf"
    )



# =================================================
# DELETE REPORT
# =================================================
@app.route("/report/<report_id>/delete", methods=["POST"])
def delete_report(report_id):
    if not login_required():
        return redirect(url_for("login"))

    report = reports.find_one({
        "_id": ObjectId(report_id),
        "user_id": session["user_id"]
    })

    if report:
        file_path = os.path.join(UPLOAD_FOLDER, report["original_file"])
        if os.path.exists(file_path):
            os.remove(file_path)

        reports.delete_one({"_id": ObjectId(report_id)})

    return redirect(url_for("documents"))




# =================================================
# REGISTER
# =================================================
@app.route("/register", methods=["GET", "POST"])
def register():
    # 🔹 GET → show register page
    if request.method == "GET":
        return render_template("register.html")

    # 🔹 POST → handle registration
    email = request.form.get("email")
    password = request.form.get("password")

    # ✅ EMAIL VALIDATION
    if not is_valid_email(email):
        return render_template(
            "register.html",
            error="Invalid email format"
        )

    # ✅ PASSWORD VALIDATION
    if not is_strong_password(password):
        return render_template(
            "register.html",
            error="Password must be at least 8 characters, include 1 capital letter and 1 special character"
        )

    # ✅ DUPLICATE CHECK
    if users.find_one({"email": email}):
        return render_template(
            "register.html",
            error="Email already registered"
        )

    # ✅ CREATE USER
    users.insert_one({
        "email": email,
        "password": generate_password_hash(
            password,
            method="pbkdf2:sha256"
        ),
        "created_at": datetime.utcnow()
    })

    # ✅ SEND WELCOME EMAIL (INFORMATIONAL)
    try:
        send_welcome_email(email)
    except Exception as e:
        print("Welcome email failed:", e)
        # Do NOT block registration if email fails

    # ✅ SHOW SUCCESS STATE (NO REDIRECT)
    return render_template(
        "register.html",
        success=True,
        email=email
    )


# =================================================
# LOGIN
# =================================================
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        user = users.find_one({"email": request.form["email"]})
        if not user or not check_password_hash(
            user["password"], request.form["password"]
        ):
            return render_template("login.html", error="Invalid credentials")

        session.clear()
        session["user_id"] = str(user["_id"])
        return redirect(url_for("index"))

    return render_template("login.html")



# =================================================
# FORGOT PASSWORD
# =================================================
@app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password():
    if request.method == "POST":
        email = request.form.get("email")

        if not is_valid_email(email):
            return render_template("forgot_password.html", error="Invalid email")

        user = users.find_one({"email": email})
        if not user:
            return render_template("forgot_password.html", error="Email not registered")

        otp = generate_otp()
        users.update_one(
            {"email": email},
            {"$set": {
                "reset_otp": otp,
                "otp_expiry": datetime.utcnow() + timedelta(minutes=10)
            }}
        )

        send_otp_email(email, otp)
        session["reset_email"] = email
        return redirect(url_for("reset_password"))

    return render_template("forgot_password.html")


# =================================================
# RESET PASSWORD
# =================================================
@app.route("/reset-password", methods=["GET", "POST"])
def reset_password():
    email = session.get("reset_email")
    if not email:
        return redirect(url_for("login"))

    if request.method == "POST":
        otp = request.form.get("otp")
        password = request.form.get("password")

        user = users.find_one({"email": email})
        if not user or user.get("reset_otp") != otp:
            return render_template("reset_password.html", error="Invalid OTP")

        if datetime.utcnow() > user.get("otp_expiry"):
            return render_template("reset_password.html", error="OTP expired")

        if not is_strong_password(password):
            return render_template("reset_password.html", error="Weak password")

        users.update_one(
            {"email": email},
            {
                "$set": {
                    "password": generate_password_hash(password, method="pbkdf2:sha256")
                },
                "$unset": {
                    "reset_otp": "",
                    "otp_expiry": ""
                }
            }
        )

        session.pop("reset_email", None)
        return render_template("reset_success.html")

    return render_template("reset_password.html")


# =================================================
# LOGOUT
# =================================================
@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))

# ---------------- HOME ----------------
@app.route("/")
def home():
    return render_template(
        "home.html",
        navbar_type="home"
    )



# ================= HELP CENTER =================

@app.route("/help")
def help_page():
    return render_template(
        "help/help.html",
        navbar_type="help"
    )



@app.route("/help/topics")
def help_topics():
    return render_template("help/help-topic.html")


from flask import render_template, redirect

@app.route("/help/article/<slug>")
def help_article(slug):

    articles = {

        "replace-doctor": {
            "title": "Can MediHub replace my doctor?",
            "content": [
                "No. MediHub is not designed to replace doctors or certified medical professionals. It is an AI-powered assistance tool created to help users better understand their medical reports and health data.",

                "MediHub explains medical terms, lab values, and highlights abnormal results in a simple and easy-to-understand manner. This helps users become more informed about their health reports before consulting a healthcare provider.",

                "The platform does not provide diagnoses, prescriptions, or treatment plans. All insights generated by MediHub are informational and should not be considered medical advice.",

                "Medical decisions require clinical judgment, physical examination, and patient history, which only a qualified doctor can provide. MediHub works best as a supportive tool alongside professional medical care.",

                "Always consult a certified doctor or healthcare professional for diagnosis, treatment, or medical decisions."
            ]
        },

        "data-security": {
            "title": "Is my data secure?",
            "content": [
                "Yes. MediHub takes data privacy and security very seriously. All uploaded medical data is encrypted using industry-standard security protocols.",

                "Your reports are securely stored and protected against unauthorized access. We follow best practices in data handling, storage, and transmission to ensure confidentiality.",

                "MediHub does not sell, share, or distribute your personal or medical data to third parties for marketing or commercial purposes.",

                "Access to sensitive data is restricted and monitored, and security measures are continuously updated to address emerging threats.",

                "Users remain in control of their data and can choose when and how to use MediHub’s services with confidence."
            ]
        },

        "supported-reports": {
            "title": "What reports are supported?",
            "content": [
                "MediHub supports commonly prescribed laboratory reports including CBC, diabetes reports, liver function tests, kidney function tests, and other routine blood investigations.",

                "Each report is analyzed to help users understand key parameters, normal reference ranges, and possible abnormalities.",

                "Both scanned PDF reports and digitally generated lab reports are supported using OCR technology.",

                "Digital reports allow more accurate structured data extraction for better insights.",

                "Support for additional report types is continuously expanding."
            ]
        },

        "analysis-method": {
            "title": "How does MediHub analyze reports?",
            "content": [
                "MediHub uses OCR technology to extract values, units, and test names from reports.",

                "Machine learning models analyze these values against standard medical ranges.",

                "Rule-based logic explains abnormal findings in simple language.",

                "The system focuses on clarity rather than medical jargon.",

                "All insights are informational and should be discussed with a doctor."
            ]
        },

        # ✅ MATCHES: /help/article/upload-report
        "upload-report": {
            "title": "How do I upload a lab report?",
            "content": [
                "MediHub allows you to upload medical reports in PDF or image format.",
                "You can upload scanned or digitally generated lab reports.",
                "OCR technology extracts values securely from the document.",
                "Ensure reports are clear and readable for best accuracy.",
                "Uploaded reports are encrypted and never shared without consent."
            ]
        },

        # ✅ MATCHES: /help/article/read-results
        "read-results": {
            "title": "How do I understand my test results?",
            "content": [
                "MediHub converts complex medical terms into easy explanations.",
                "Normal and abnormal values are clearly highlighted.",
                "Each test includes context on what it means for your health.",
                "Users are encouraged to consult doctors for decisions.",
                "This feature supports—not replaces—medical advice."
            ]
        },

        # ✅ MATCHES: /help/article/ai-accuracy
        "ai-accuracy": {
            "title": "How accurate is AI analysis?",
            "content": [
                "MediHub uses trained machine learning models on medical datasets.",
                "Accuracy depends on report quality and clarity.",
                "AI helps detect potential abnormalities and trends.",
                "Medical rules ensure explanations are safe and responsible.",
                "Final medical decisions should always involve professionals."
            ]
        }
    }

    article = articles.get(slug)
    if not article:
        return redirect("/help")

    return render_template(
        "help/help-article.html",
        article=article,
        navbar_type="help"
    )



# ---------------- CONTACT SUPPORT ----------------
@app.route("/contact", methods=["GET"])
def contact():
    return render_template("help/contact.html")


# =================================================
# RUN
# =================================================
import os

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port, debug=False)
