from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas


# =====================================================
# PDF GENERATOR (PRESENTATION ONLY — NO MEDICAL LOGIC)
# =====================================================
def generate_digital_report(report):
    """
    Generates a PROFESSIONAL, CONSISTENT PDF medical report

    IMPORTANT:
    - No medical logic
    - No reference ranges
    - No status computation
    - Uses flags generated by lab_flags.py ONLY
    """

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    patient = report.get("patient", {})
    lab_values = report.get("lab_values", {})
    flags = report.get("flags", {})
    created_at = report.get("created_at", datetime.utcnow())

    y = height - 2 * cm

    # =================================================
    # HEADER
    # =================================================
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawCentredString(width / 2, y, "MediHub – Digital Medical Report")
    y -= 1.1 * cm

    pdf.setFont("Helvetica", 10)
    pdf.drawCentredString(
        width / 2,
        y,
        "AI-assisted laboratory report analysis"
    )
    y -= 1.4 * cm

    # =================================================
    # PATIENT INFO
    # =================================================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(2 * cm, y, "Patient Information")
    y -= 0.8 * cm

    pdf.setFont("Helvetica", 10)
    pdf.drawString(2 * cm, y, f"Name        : {patient.get('name', 'N/A')}")
    y -= 0.5 * cm

    pdf.drawString(
        2 * cm,
        y,
        f"Age / Gender: {patient.get('age', 'N/A')} / {patient.get('gender', 'N/A')}"
    )
    y -= 0.5 * cm

    pdf.drawString(
        2 * cm,
        y,
        f"Report Date : {created_at.strftime('%d %b %Y')}"
    )
    y -= 1.2 * cm

    # =================================================
    # TABLE HEADER
    # =================================================
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(2 * cm, y, "Test")
    pdf.drawString(7.5 * cm, y, "Value")
    pdf.drawString(10.5 * cm, y, "Status")
    pdf.drawString(13.5 * cm, y, "Reference")
    y -= 0.4 * cm

    pdf.line(2 * cm, y, width - 2 * cm, y)
    y -= 0.5 * cm

    # =================================================
    # TABLE ROWS (FLAGS ARE SOURCE OF TRUTH)
    # =================================================
    pdf.setFont("Helvetica", 10)

    for test, flag in flags.items():
        value = flag["value"]
        status = flag["status"].upper()
        ref = flag["range"]

        pdf.drawString(2 * cm, y, test.replace("_", " ").upper())
        pdf.drawString(7.5 * cm, y, str(value))
        pdf.drawString(10.5 * cm, y, status)
        pdf.drawString(13.5 * cm, y, ref)

        y -= 0.45 * cm

        if y < 2 * cm:
            pdf.showPage()
            pdf.setFont("Helvetica", 10)
            y = height - 2 * cm

    # =================================================
    # FOOTER
    # =================================================
    y -= 0.8 * cm
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.drawString(
        2 * cm,
        y,
        "Disclaimer: This AI-generated report is for informational purposes only."
    )
    y -= 0.4 * cm

    pdf.drawString(
        2 * cm,
        y,
        "Generated by MediHub AI • Do not use for self-diagnosis"
    )

    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    return buffer
