# ocr/medi_hub_detector.py

def is_medihub_generated(text: str) -> bool:
    """
    Detect if uploaded PDF was generated by MediHub
    """
    if not text:
        return False

    signatures = [
        "Generated by MediHub",
        "MediHub – Digital Medical Report",
        "AI-assisted laboratory report analysis"
    ]

    text_lower = text.lower()

    return any(sig.lower() in text_lower for sig in signatures)
